### ISSUE TITLE
It doesn't work :(

### ISSUE THREAD

**Issue by 45025** [10se1ucgo/LoLTrivia#7]
The bot is online but won't respond when prompted with !trivia

**Comment by 10se1ucgo** [comment]
Sorry, Discord has been tightening down on bots' abilities to read messages and server member lists. The idea is IIRC to crack down on spam bots, but really all they do is make our lives harder as developers since practically 0 people use verified bots for spam. The other angle they're going for I believe is data privacy, which IMO is pretty rich coming from Discord given that even they do not allow us to delete all our data from the platform easily.

Sorry for the rant, but **I've enabled a temporary override that should let the bot function at least until October 1st, 2022.** I'll restart the bot in a few minutes and hopefully it should start working again. If not, I'll take a closer look once I get home today.

I'll also mention that the hosting service I've been using for the bot has recently announced that they will be discontinuing their free tier in around November. I don't particularly see myself spending money on keeping the bot up, mostly since I don't think very many people use it. Once that happens, you're likely better off downloading the bot's code and running it locally instead, which I can provide instructions for if interested. Otherwise, if enough people complain I will consider looking for a new home for the bot :)

**Comment by 10se1ucgo** [comment]
Looks like its working now.

**Comment by 45025** [comment]
Yes, it is working, thank you!
Is there any way I can message you? We'd hate to see the bot go and I'd be interested to host it locally, but I'd definitely need help with setting that up.
